import Navbar from "@/components/Navbar";
import "./globals.css";
import ProviderRedux from "./provider";
import UserMessage from "./UserMessage";
import ComapnyMessage from "./CompanyMessage";
import JobMessage from "./JobMessage";

export const metadata = {
  title: "EmployaX",
  description: "Generated by create next app",
  icons:{
    icon:'/vercel.jpg'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-amber-50">
        <ProviderRedux>
          <Navbar /> {children}
          <UserMessage/>
          <ComapnyMessage/>
          <JobMessage/>
        </ProviderRedux>
      </body>
    </html>
  );
}
